package com.training.esb.esb_adapter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-06-03T09:10:48.489-04:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "AddressService",
                  wsdlLocation = "file:/C:/Coding/Developer/Technology/Camel/Projects/Sample/springboot-camel-soapws/src/main/resources/wsdl/address.wsdl",
                  targetNamespace = "http://esb.training.com/esb_adapter")
public class AddressService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esb.training.com/esb_adapter", "AddressService");
    public final static QName AddressPort = new QName("http://esb.training.com/esb_adapter", "AddressPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Coding/Developer/Technology/Camel/Projects/Sample/springboot-camel-soapws/src/main/resources/wsdl/address.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AddressService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Coding/Developer/Technology/Camel/Projects/Sample/springboot-camel-soapws/src/main/resources/wsdl/address.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AddressService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AddressService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AddressService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AddressService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AddressService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AddressEndpoint
     */
    @WebEndpoint(name = "AddressPort")
    public AddressEndpoint getAddressPort() {
        return super.getPort(AddressPort, AddressEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressEndpoint
     */
    @WebEndpoint(name = "AddressPort")
    public AddressEndpoint getAddressPort(WebServiceFeature... features) {
        return super.getPort(AddressPort, AddressEndpoint.class, features);
    }

}
