package com.training.esb.esb_adapter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-06-03T09:10:48.392-04:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://esb.training.com/esb_adapter", name = "AddressEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AddressEndpoint {

    @WebMethod(action = "http://esb.training.com/esb_adapter/Address/getAddress")
    @WebResult(name = "getAddressResponse", targetNamespace = "http://esb.training.com/esb_adapter", partName = "out")
    public GetAddressResponse getAddress(

        @WebParam(partName = "in", name = "getAddressRequest", targetNamespace = "http://esb.training.com/esb_adapter")
        GetAddressRequest in
    );
}
